#!/bin/sh
set -e
DKMS_NAME=hello
DKMS_VERSION=0.1
case "$1" in
	remove|upgrade|deconfigure)
		if [ "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
			dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all || true
		fi
	;;
esac
exit 0
